image: rust

check-format:
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

check-lint:
  before_script:
    - apt update -y -qq
    - apt install -y -qq --no-install-recommends git clang make pkg-config nettle-dev libssl-dev capnproto ca-certificates
    - apt clean
    - rustup component add clippy
  script:
    - cargo clippy --all

unit-tests:
  before_script:
    - apt update -y -qq
    - apt install -y -qq --no-install-recommends git clang make pkg-config nettle-dev libssl-dev capnproto ca-certificates
    - apt clean
  script:
    - cargo test --all --verbose

end-to-end-tests:
  before_script:
    - apt update -y -qq
    - apt install -y -qq --no-install-recommends git emacs python3 python3-venv clang make pkg-config nettle-dev libssl-dev capnproto ca-certificates
    - apt clean
  script:
    - emacs -Q --batch --eval "
      (progn
        (require 'ob-tangle)
        (dolist (file command-line-args-left)
          (with-current-buffer (find-file-noselect file)
            (org-babel-tangle))))" README.org
    - source README.sh
    - python3 README.python

pages:
  script:
pages:
  script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends emacs org-mode texlive-latex-extra texlive-latex-base texlive-fonts-recommended lmodern texlive-plain-generic
    - emacs -Q --batch README.org -f org-latex-export-to-pdf
    - curl -o /etc/emacs/htmlize.el https://raw.githubusercontent.com/hniksic/emacs-htmlize/master/htmlize.el
    - emacs -Q --batch README.org --eval "(load \"/etc/emacs/htmlize.el\")" -f org-html-export-to-html
    - emacs -Q --batch CONTRIBUTING.org --eval "(load \"/etc/emacs/htmlize.el\")" -f org-html-export-to-html
    - mkdir public
    - mv README.html public/index.html
    - mv README.pdf public
  artifacts:
    paths:
      - public
