[package]
name = "pysequoia"
version = "0.1.16"
edition = "2021"

# The crate is useless for Rust clients, it's mainly used via Python:
# https://pypi.org/project/pysequoia/
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pysequoia"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.69"
once_cell = "1.17.1"
openpgp-card-pcsc = "0.3.0"
openpgp-card-sequoia = { version = "0.1.1", default-features = false }
openpgp-cert-d = "0.1.0"
pyo3 = { version = "0.18", features = ["extension-module", "anyhow"] }
pyo3-asyncio = { version = "0.18", features = ["tokio-runtime"] }
reqwest = "0.11.14"
sequoia-net = "0.26.0"
sequoia-openpgp = { version = "1.13", default-features = false, features = ["compression"]  }
testresult = "0.3"

[target.'cfg(not(windows))'.dependencies]
sequoia-openpgp = { version = "1", default-features = false, features = ["crypto-nettle"]  }

[target.'cfg(windows)'.dependencies]
sequoia-openpgp = { version = "1", default-features = false, features = ["crypto-cng"] }
