[package]
name = "pysequoia"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pysequoia"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.66"
pyo3 = { version = "0.17.3", features = ["extension-module", "anyhow"] }
pyo3-asyncio = { version = "0.17.0", features = ["tokio-runtime"] }
sequoia-net = "0.26.0"
sequoia-openpgp = "1.11.0"
testresult = "0.1"
