name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        toolchain: [nightly, beta, stable]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build --build-arg RUST_TOOLCHAIN=${{ matrix.toolchain }} --build-arg SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) --platform linux/amd64 --file ci/build.dockerfile .
